version: "3.8"

services:
  database:
    build:
      context: .
      dockerfile: ./docker/database
    volumes:
      - avito-unit-job:/var/lib/postgresql/data

  redis:
    image: "redis:6.0.8-alpine"

  app:
    build:
      context: .
      dockerfile: ./docker/app
    ports:
      - 8080:8080
    depends_on:
      - database
      - redis

volumes:
  avito-unit-job:
