version: "3.8"

services:
  database:
    build:
      context: .
      dockerfile: ./docker/database
    volumes:
      - avito-unit-job:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./docker/app
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  avito-unit-job:
