// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA252db63DecodeGithubComKonstantinProninAvitoUnitJobBackendInternalCurrencyModel(in *jlexer.Lexer, out *ExchangeRates) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "base":
			out.Base = string(in.String())
		case "date":
			out.Date = string(in.String())
		case "rates":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Rates = make(map[string]float32)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 float32
					v1 = float32(in.Float32())
					(out.Rates)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA252db63EncodeGithubComKonstantinProninAvitoUnitJobBackendInternalCurrencyModel(out *jwriter.Writer, in ExchangeRates) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"base\":"
		out.RawString(prefix[1:])
		out.String(string(in.Base))
	}
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix)
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"rates\":"
		out.RawString(prefix)
		if in.Rates == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Rates {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				out.Float32(float32(v2Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExchangeRates) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA252db63EncodeGithubComKonstantinProninAvitoUnitJobBackendInternalCurrencyModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExchangeRates) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA252db63EncodeGithubComKonstantinProninAvitoUnitJobBackendInternalCurrencyModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExchangeRates) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA252db63DecodeGithubComKonstantinProninAvitoUnitJobBackendInternalCurrencyModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExchangeRates) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA252db63DecodeGithubComKonstantinProninAvitoUnitJobBackendInternalCurrencyModel(l, v)
}
