name: avito-unit-job integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26

  test:
    runs-on: ubuntu-latest
    needs: golangci
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...